### ISSUE TITLE
feature request: Config option for quality

### ISSUE THREAD

**Issue by JustCauseWhyNot** [zfleeman/ffmpeg4discord#29]
Allow setting quality settings with a flag, or in a config file. Example for vp9 would be able to set `-deadline=best`, and `-cpu-utliization=5`. Instead of using the options predefined in the two_pass script.

This would awesome if you implemented this instead of having to build your project from source to set those options.

**Comment by JustCauseWhyNot** [comment]
Sorry if you want me to open another issue instead. I've another feature request. Allow setting output in config. If that's already supported than I must be doing [something](https://paste.gentoo.zip/LUhw2b6w) wrong. Alongside that perhaps have random generated string of characters for file name. And lastly and issue I've discovered is that the output video is slightly shorter than the input video, but times is disabled in my config.

Thank you for this awesome tool!

**Comment by zfleeman** [comment]
Setting the quality settings with a flag is an interesting idea, and it is one I will pursue because I hate seeing the hard-coded values in `twopass.py`. We'll keep this issue for that.

If you _could_ create a new issue for the "specify output in config" I'd appreciate it. That's something I should revisit anyway -- the config json is a kind of an underdeveloped afterthought.

As for the video being slightly shorter, I'm sure this is because this tool is (for now) accurate down to the second, and not microsecond. I'm pretty sure ffmpeg can support timestamps formatted like this `00:00:00:000`, so this is something that `ffmpeg-python` may be able to support unless I'm wildly off base, here. "Microsecond support" could be a separate issue as well.

Also, what is mpv?
> when I trim a video in mpv

**Comment by JustCauseWhyNot** [comment]
This is [mpv](https://github.com/mpv-player/mpv). I'll make a new issue for the config. And respond more in detail soon.

**Comment by JustCauseWhyNot** [comment]
> Setting the quality/speed settings with a flag is an interesting idea, and it is one I will pursue because I hate seeing the hard-coded values in twopass.py. We'll keep this issue for that.

That's great to hear

> As for the video being slightly shorter, I'm sure this is because this tool is (for now) accurate down to the second, and not microsecond. I'm pretty sure ffmpeg can support timestamps formatted like this 00:00:00.000, so this is something that ffmpeg-python may be able to support unless I'm wildly off base, here. "Microsecond support" could be a separate issue as well.

I sorta though that may have been the case, but I didn't know for sure. For now I'll make sure to compensate for that.
